# Generated by Django 2.1.7 on 2019-03-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, help_text='This is the service name offered by the goodvud web solutions.', max_length=255, null=True)),
                ('service_base_image', models.ImageField(blank=True, help_text='This is the base image of the service that will be displayed on all the layouts.', max_length=255, null=True, upload_to='')),
                ('service_gallery_images', models.ImageField(blank=True, help_text='This is the main gallery images of the service that will be displayed in the form of carousel.', max_length=255, null=True, upload_to='')),
                ('service_about', models.CharField(blank=True, help_text='This contains all the details about the service.', max_length=1000, null=True)),
            ],
        ),
    ]
